# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.flexBART_fit <- function(Y_train, tX_cont_train, tX_cat_train, tX_cont_test, tX_cat_test, unif_cuts, cutpoints_list, cat_levels_list, graph_split, graph_cut_type, adj_support_list, rc_split, prob_rc, a_rc, b_rc, sparse, a_u, b_u, mu0, tau, lambda, nu, M, nd, burn, thin, save_trees, verbose, print_every, check_ss_map = FALSE) {
    .Call('_flexBART_flexBART_fit', PACKAGE = 'flexBART', Y_train, tX_cont_train, tX_cat_train, tX_cont_test, tX_cat_test, unif_cuts, cutpoints_list, cat_levels_list, graph_split, graph_cut_type, adj_support_list, rc_split, prob_rc, a_rc, b_rc, sparse, a_u, b_u, mu0, tau, lambda, nu, M, nd, burn, thin, save_trees, verbose, print_every, check_ss_map)
}

.flexBARTfast_fit <- function(Y_train, tX_cont_train, tX_cat_train, tX_cont_test, tX_cat_test, unif_cuts, cutpoints_list, cat_levels_list, graph_split, graph_cut_type, adj_support_list, rc_split, prob_rc, a_rc, b_rc, sparse, a_u, b_u, mu0, tau, lambda, nu, M, nd, burn, thin, save_trees, verbose, print_every, check_ss_map = FALSE) {
    .Call('_flexBART_flexBARTfast_fit', PACKAGE = 'flexBART', Y_train, tX_cont_train, tX_cat_train, tX_cont_test, tX_cat_test, unif_cuts, cutpoints_list, cat_levels_list, graph_split, graph_cut_type, adj_support_list, rc_split, prob_rc, a_rc, b_rc, sparse, a_u, b_u, mu0, tau, lambda, nu, M, nd, burn, thin, save_trees, verbose, print_every, check_ss_map)
}

predict_flexBART <- function(tree_draws, tX_cont, tX_cat, cat_levels_list, adj_support_list, graph_split, verbose = TRUE, print_every = 50L) {
    .Call('_flexBART_predict_flexBART', PACKAGE = 'flexBART', tree_draws, tX_cont, tX_cat, cat_levels_list, adj_support_list, graph_split, verbose, print_every)
}

.draw_tree <- function(tX_cont, tX_cat, unif_cuts, cutpoints_list, cat_levels_list, graph_split, graph_cut_type, adj_support_list, rc_split, prob_rc, alpha, beta, mu0, tau) {
    .Call('_flexBART_drawTree', PACKAGE = 'flexBART', tX_cont, tX_cat, unif_cuts, cutpoints_list, cat_levels_list, graph_split, graph_cut_type, adj_support_list, rc_split, prob_rc, alpha, beta, mu0, tau)
}

.draw_ensemble <- function(tX_cont, tX_cat, unif_cuts, cutpoints_list, cat_levels_list, graph_split, graph_cut_type, adj_support_list, rc_split, prob_rc, alpha, beta, mu0, tau, M, verbose, print_every) {
    .Call('_flexBART_drawEnsemble', PACKAGE = 'flexBART', tX_cont, tX_cat, unif_cuts, cutpoints_list, cat_levels_list, graph_split, graph_cut_type, adj_support_list, rc_split, prob_rc, alpha, beta, mu0, tau, M, verbose, print_every)
}

