# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.detect_nesting <- function(X_cat, K, p_cont = 0L) {
    .Call('_flexBART_detect_nesting', PACKAGE = 'flexBART', X_cat, K, p_cont)
}

._multi_fit <- function(Y_train, cov_ensm, tZ_train, tX_cont_train, tX_cat_train, tZ_test, tX_cont_test, tX_cat_test, cutpoints_list, cat_levels_list, edge_mat_list, nest_list, graph_cut_type, sparse, a_u, b_u, nest_v, nest_v_option, nest_c, M_vec, alpha_vec, beta_vec, mu0_vec, tau_vec, sigest, nu, lambda, nd, burn, thin, save_samples, save_trees, verbose, print_every) {
    .Call('_flexBART_multi_fit', PACKAGE = 'flexBART', Y_train, cov_ensm, tZ_train, tX_cont_train, tX_cat_train, tZ_test, tX_cont_test, tX_cat_test, cutpoints_list, cat_levels_list, edge_mat_list, nest_list, graph_cut_type, sparse, a_u, b_u, nest_v, nest_v_option, nest_c, M_vec, alpha_vec, beta_vec, mu0_vec, tau_vec, sigest, nu, lambda, nd, burn, thin, save_samples, save_trees, verbose, print_every)
}

.single_ensm_predict <- function(tree_draws, tX_cont, tX_cat, M, probit, verbose, print_every) {
    .Call('_flexBART_single_predict', PACKAGE = 'flexBART', tree_draws, tX_cont, tX_cat, M, probit, verbose, print_every)
}

.multi_ensm_predict <- function(tree_draws, tZ, tX_cont, tX_cat, M_vec, verbose, print_every) {
    .Call('_flexBART_multi_predict', PACKAGE = 'flexBART', tree_draws, tZ, tX_cont, tX_cat, M_vec, verbose, print_every)
}

rescale_beta_mean <- function(beta_input, y_mean, y_sd, z_mean, z_sd, z_col_id) {
    .Call('_flexBART_rescale_beta_mean', PACKAGE = 'flexBART', beta_input, y_mean, y_sd, z_mean, z_sd, z_col_id)
}

rescale_beta <- function(beta_input, y_mean, y_sd, z_mean, z_sd, z_col_id) {
    .Call('_flexBART_rescale_beta', PACKAGE = 'flexBART', beta_input, y_mean, y_sd, z_mean, z_sd, z_col_id)
}

._draw_tree <- function(tX_cont, tX_cat, cov_ensm, cutpoints_list, cat_levels_list, edge_mat_list, nest_list, graph_cut_type, nest_v, nest_v_option, nest_c, alpha, beta, nd, verbose, print_every) {
    .Call('_flexBART_drawTree', PACKAGE = 'flexBART', tX_cont, tX_cat, cov_ensm, cutpoints_list, cat_levels_list, edge_mat_list, nest_list, graph_cut_type, nest_v, nest_v_option, nest_c, alpha, beta, nd, verbose, print_every)
}

.single_fit <- function(Y_train, cov_ensm, tX_cont_train, tX_cat_train, tX_cont_test, tX_cat_test, cutpoints_list, cat_levels_list, edge_mat_list, nest_list, graph_cut_type, sparse, a_u, b_u, nest_v, nest_v_option, nest_c, M, alpha, beta, mu0, tau, sigest, nu, lambda, nd, burn, thin, save_samples, save_trees, verbose, print_every) {
    .Call('_flexBART_single_fit', PACKAGE = 'flexBART', Y_train, cov_ensm, tX_cont_train, tX_cat_train, tX_cont_test, tX_cat_test, cutpoints_list, cat_levels_list, edge_mat_list, nest_list, graph_cut_type, sparse, a_u, b_u, nest_v, nest_v_option, nest_c, M, alpha, beta, mu0, tau, sigest, nu, lambda, nd, burn, thin, save_samples, save_trees, verbose, print_every)
}

.single_fit_probit <- function(Y_train, cov_ensm, tX_cont_train, tX_cat_train, tX_cont_test, tX_cat_test, cutpoints_list, cat_levels_list, edge_mat_list, nest_list, graph_cut_type, sparse, a_u, b_u, nest_v, nest_v_option, nest_c, M, alpha, beta, mu0, tau, nd, burn, thin, save_samples, save_trees, verbose, print_every) {
    .Call('_flexBART_single_probit_fit', PACKAGE = 'flexBART', Y_train, cov_ensm, tX_cont_train, tX_cat_train, tX_cont_test, tX_cat_test, cutpoints_list, cat_levels_list, edge_mat_list, nest_list, graph_cut_type, sparse, a_u, b_u, nest_v, nest_v_option, nest_c, M, alpha, beta, mu0, tau, nd, burn, thin, save_samples, save_trees, verbose, print_every)
}

