---
title: "Comparison to other implementations"
knitr:
  opts_chunk:
    collapse: true
    comment: '#>'
---




## Basic BART Model


## Categorical Features

<!--
  Write a little 




```{r}
#| label: setup-containers
rmse_train <- c("flexBART" = NA, "BART" = NA)
rmse_test <- c("flexBART" = NA, "BART" = NA)
timing <- c("flexBART" = NA, "BART" = NA)
```

```{r}
#| label: comparison-flexBART
#| message: false
#| output: false
#| results: hide

flex_fit <-
  flexBART::flexBART(formula = Y~bart(.),
                     train_data = train_data,
                     test_data = test_data,
                     M = 200)
rmse_train["flexBART"] <- sqrt(mean( (mu_train - flex_fit$yhat.train.mean)^2 ))
rmse_test["flexBART"] <- sqrt(mean( (mu_test - flex_fit$yhat.test.mean)^2 ))
timing["flexBART"] <- sum(flex_fit$timing) # total run time over all chains
```


To make the comparison fair, we'll run 4 `BART::wbart` chains for the same number of iterations with the argument `sparse = TRUE`.
```{r fit-bart, results='hide', cache=TRUE}
#| label: comparison-wbart
#| message: false
#| output: false
#| results: hide

bart_time <- rep(NA, times = 4)
bart_train <- rep(0, times = n_train)
bart_test <- rep(0, times = n_test)
for(cix in 1:4){
  tmp_time <-
    system.time(
      bart_fit <- 
        BART::wbart(x.train = train_data[,colnames(train_data) != "Y"], 
                    y.train = train_data[,"Y"], 
                    x.test = test_data[,colnames(test_data) != "Y"],
                    sparse = TRUE,
                  ndpost = 1000, nskip = 1000))
  bart_train <-
    bart_train + bart_fit$yhat.train.mean/4
  bart_test <-
    bart_test + bart_fit$yhat.test.mean/4
  bart_time[cix] <- tmp_time["elapsed"]
}
rmse_train["BART"] <- sqrt(mean( (mu_train - bart_train)^2 ))
rmse_test["BART"] <- sqrt(mean( (mu_test - bart_test)^2 ))
timing["BART"] <- sum(bart_time)
```


Besides the handling of categorical covariates, there are some important implementation differences between **BART** and **flexBART**.
First, **BART** creates a grid of 100 potential cutpoints (this is controlled by the `numcut` argument of `BART::wbart()`) for each continuous predictor
**flexBART**, by contrast, draws cutpoints uniformly from the interval of available values. 
Second, **BART** initializes the residual standard deviation $\sigma$ based on an estimated linear model (see [here](https://github.com/cran/BART/blob/master/R/wbart.R#L95-L101)).
**flexBART** instead uses the root mean square of the residuals from a cross-validated LASSO fit. 
Because of these differences, we should not expect to obtain identical results from **flexxBART** and **BART**.
Nevertheless, at least for these data, the two implementations display similar in-sample and out-of-sample predictive performance.
We see, additionally, that **flexBART** is much faster than **BART**.

```{r}
#| label: comparison-performance
print("Training RMSE")
print(round(rmse_train, digits = 3))

print("Testing RMSE")
print(round(rmse_test, digits = 3))

print("Timing (seconds):")
print(round(timing, digits = 3))

```
-->